// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJXm4_VSy0DrpLbEDn2SsPuBuPaVEqvmk',
    appId: '1:372786952763:web:20946e64199be75d97ba1e',
    messagingSenderId: '372786952763',
    projectId: 'ace-interview-9b80f',
    authDomain: 'ace-interview-9b80f.firebaseapp.com',
    storageBucket: 'ace-interview-9b80f.firebasestorage.app',
    measurementId: 'G-W9NQ56WD4P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-E48sit3E5F__NSWx6MoKtftzLZYDMI4',
    appId: '1:372786952763:android:34508c8f7f0edefc97ba1e',
    messagingSenderId: '372786952763',
    projectId: 'ace-interview-9b80f',
    storageBucket: 'ace-interview-9b80f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChEntJ4PPqe1HeF7fT-4IOTa8RQQVrVFw',
    appId: '1:372786952763:ios:65440944653dc54397ba1e',
    messagingSenderId: '372786952763',
    projectId: 'ace-interview-9b80f',
    storageBucket: 'ace-interview-9b80f.firebasestorage.app',
    iosBundleId: 'com.example.aceInterview',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChEntJ4PPqe1HeF7fT-4IOTa8RQQVrVFw',
    appId: '1:372786952763:ios:65440944653dc54397ba1e',
    messagingSenderId: '372786952763',
    projectId: 'ace-interview-9b80f',
    storageBucket: 'ace-interview-9b80f.firebasestorage.app',
    iosBundleId: 'com.example.aceInterview',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJXm4_VSy0DrpLbEDn2SsPuBuPaVEqvmk',
    appId: '1:372786952763:web:7deedc9fb2c113fb97ba1e',
    messagingSenderId: '372786952763',
    projectId: 'ace-interview-9b80f',
    authDomain: 'ace-interview-9b80f.firebaseapp.com',
    storageBucket: 'ace-interview-9b80f.firebasestorage.app',
    measurementId: 'G-42SQ3XWPG7',
  );
}
